### ISSUE TITLE
Publish quantized-mesh-decoder 1.1.3 to npmjs.com

### ISSUE THREAD

**Issue by tsteenbe** [heremaps/quantized-mesh-decoder#16]
This issue will be used to track open items to be resolved prior to publication

Issues found:
- Update copyrights to 2019
- Fix the various security vulnerabilities found by `npm audit`/`yarn audit`
- Switch to `yarn` to align with `harp.gl`?

**Comment by tsteenbe** [comment]
Update copyrights done in https://github.com/heremaps/quantized-mesh-decoder/pull/15

**Comment by tsteenbe** [comment]
@NicolasNeubauer  several security vulnerabilities are reported. Can you resolve these?

**Comment by NicolasNeubauer** [comment]
Yes, see #17
