### ISSUE TITLE
"Unknown extension with id 4"

### ISSUE THREAD

**Issue by bbbbx** [heremaps/quantized-mesh-decoder#21]
Hi, thanks the decoder, but it couldn't decode metadata extension, [https://github.com/CesiumGS/quantized-mesh#metadata](https://github.com/CesiumGS/quantized-mesh#metadata)

**Comment by mykolaharmash** [comment]
Hi! If possible, please make a PR to support the extension, this will be the fastest way to fix this. Thank you!
